version: '3'

dotenv: ['{{.HOME}}/{{.MACHINE_NAME}}/.env', '{{.HOME}}/.env', '.env']

run: when_changed


tasks:
  setup:
    status:
      - test -d .vercel
    cmds:
      - |
        npx --yes \
          vercel --token "$VERCEL_TOKEN" \
            link --yes \
              --project esperoj

  deploy:
    deps: [setup]
    cmds:
      - cp -r "${ESPEROJ_CONFIG_FILE}" "$ESPEROJ_SCRIPTS_FOLDER" .
      - defer: rm -rf esperoj.toml.7z esperoj-scripts
      - |
        npx --yes \
          vercel --token "$VERCEL_TOKEN" \
            deploy --yes --prod
